version: 1.3.1.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
build:
  project: ENetSharp.sln